mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('vulnscan.urls')),
    path('celery_progress/', include('celery_progress.urls')),
    path('admin/', admin.site.urls),
]

mysite/vulnscan/urls.py
from django.urls import path

from . import views


app_name = 'vuln'
urlpatterns = [
    path('', views.index, name='index'),
    path('scans/', views.scan_start, name='scan_start'),
    path('scani/', views.scan_work, name='scan_work'),
    path('scane/<str:task_id>', views.scan_end, name='scan_end'),
    path('vuln_info/', views.vuln_info, name='vuln_info'),
    path('check/session_test/', views.session_test, name='session_test'),
    path('check/url_access/', views.url_access, name='url_access'),
]

mysite/vulnscan/models.py
from django.db import models

# Create your models here.

mysite/vulnscan/views.py
from asyncio import base_tasks
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from vulnscan.vulntestcode import sessionLogin
from .tasks import vuln_scan
from django_celery_results.models import TaskResult
import json
import base64

# Create your views here.
def index(request):
    latest_question_list = "HI"
    context = {'latest_question_list': latest_question_list}
    return render(request, 'vulnscan/index.html', context)


def scan_start(request):
    return render(request, 'vulnscan/scan_start.html')

def scan_work(request):

    input = base64.b64decode(request.POST['content'])
    in_to_json = json.loads(input)

    task = vuln_scan.delay(in_to_json)
    return render(request, 'vulnscan/scan_work.html', {'task_id': task.task_id})

def scan_end(request, task_id):
    info = TaskResult.objects.get(task_id=task_id)
    print(info.result)
    return render(request, 'vulnscan/scan_end.html', {"info": info.result, })

def vuln_info(request):
    return render(request, 'vulnscan/vuln_info.html')

# jsonResponse

def url_access(request):
    result = sessionLogin.access_check(request.POST['url'])
    return JsonResponse({"status":result}, status=200) 

def session_test(request):
    input_data = request.POST['content']
    json_dic = json.loads(input_data)
    result = sessionLogin.session_check(json_dic['url'],json_dic['act_url'],json_dic['data'])
    return JsonResponse({"status":result}, status=200)

mysite/vulnscan/templates/vulnscan/base.html
{% load static %}
<!DOCTYPE html>

<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>OWL SCAN - Vuln Scan</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    
    <!-- Favicons -->
    <link href="{% static 'img/owl.png' %}" rel="icon">
    
    
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700" rel="stylesheet">
    <link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css' rel='stylesheet' type='text/css'>
    
    <!-- Bootstrap CSS File -->
    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    
    <!-- Libraries CSS Files -->
    <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    
    <!-- Main Stylesheet File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    
    <!-- =======================================================
        Template Name: Stanley
        Template URL: https://templatemag.com/stanley-bootstrap-freelancer-template/
        Author: TemplateMag.com
        License: https://templatemag.com/license/
    ======================================================= -->
</head>
<body>
    {% include 'vulnscan/header.html' %}
    


    {% block contents %}

    {% endblock %}
    
    {% include 'vulnscan/footer.html' %}
</body>
</html>

mysite/vulnscan/templates/vulnscan/footer.html
{% load static %}
  <!-- +++++ Footer Section +++++ -->

  <div id="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <h4>Our TEAM</h4>
          <p>
            TEAM_X_OwLs
          </p>
        </div>
        <!-- /col-lg-4 -->

        <div class="col-lg-4">
          <h4>Copyrights</h4>
          <p>
            <a href="https://www.flaticon.com/kr/free-icons/" title="검사 아이콘">Freepik</a>
          </p>
        </div>
        
        <!-- /col-lg-4 -->

        <div class="col-lg-4">
          <h4>About Project</h4>
          <p class="no_margin">2022 - Hansung University </p>
          <p>Cyber Security Capstone Design</p>
        </div>
        <!-- /col-lg-4 -->
      </div>
    </div>
  </div>

  <div id="copyrights">
    <div class="container">
      <p>
        &copy; Copyrights <strong>Stanley</strong>. All Rights Reserved
      </p>
      <div class="credits">
        <!--
          You are NOT allowed to delete the credit link to TemplateMag with free version.
          You can delete the credit link only if you bought the pro version.
          Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/stanley-bootstrap-freelancer-template/
          Licensing information: https://templatemag.com/license/
        -->
        Created with Stanley template by <a href="https://templatemag.com/">TemplateMag</a>
        
      </div>
    </div>
  </div>
  <!-- / copyrights -->
  
  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'lib/php-mail-form/validate.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}"></script>

  

mysite/vulnscan/templates/vulnscan/header.html
  <!-- Static navbar -->
  <div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'vuln:index' %}">OwL SCAN</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'vuln:scan_start' %}">Start Scan</a></li>
          <li><a href="{% url 'vuln:vuln_info' %}">Vuln Info</a></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>

mysite/vulnscan/templates/vulnscan/index.html
{% extends 'vulnscan/base.html' %}
{% load static %}
{% block contents %}


<!-- +++++ Welcome Section +++++ -->
 <div id="ww">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 centered">
        <img src="{% static 'img/owl.png' %}"style="width:150px; height:150px;" alt="owl">
        
        <h1 id="test">웹 취약점 자동 점검 서비스</h1>
        <button class="bb btn btn-lg" id="next" onClick="location.href='{% url 'vuln:scan_start' %}'">지금 바로 검사</button>
      </div>
      <!-- /col-lg-8 -->
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
  
</div>
<!-- /ww -->


<!-- +++++ Projects Section +++++ -->
<div class="navbar-inverse intro" >
  <div class="container">
    <div class="row mt">
      <div class="col-lg-10 col-lg-offset-1 centered">
        <h1 style="color:aliceblue">INTRODUCE</h1>
      </div>
      
    </div>
    
    <div class="col-lg-5 centered">
      <h2>웹 취약점 통합 검사</h2>
      <div class="circle centered">
        <img style="width: 80%; height: auto; margin-left: 25px;" src="{% static 'img/survey.png' %}">
      </div>
      <h4>KISA 취약점 안전진단 가이드를 기반으로<br/> 서버에서 노출되는 정보의 취약점과 <br/>INPUT에서 발생하는 취약점을 자동으로 점검합니다.</h3>

    </div>
    <div class="col-lg-5 col-lg-offset-2 centered">
      <h2>취약점 솔루션 보고서</h2>
      <div class="circle centered">
        <img style="width: 80%; height: auto; margin-left: 25px;" src="{% static 'img/petition.png' %}">
      </div>
      <h4>검사 결과를 직관적으로 확인할 수 있는 보고서와 <br/> 검출된 취약점의 보완 방법을 제공합니다.</h3>
    </div>
    <div class="row mt"> </div>
  </div>
</div>



{% endblock %}
  


 

 

mysite/vulnscan/templates/vulnscan/scan_start.html
{% extends 'vulnscan/base.html' %}
{% load static %}

{% block contents %}
    <div class="container pt">
        <div class="row mt">
            <div class="col-lg-6 col-lg-offset-3 centered">
                <h4><span class="highlight">검사 준비</span> > 검사 중 > 검사 완료 > 완료</h4>
                <h1>URL VALIDATION CHECK</h1>
                <hr>
                <p> 검사 시작 전 검사할 URL이 접근 가능함을 확인합니다.</p>
            </div>
        </div>  
        <div class="row mt">
            <div class="col-lg-7 col-lg-offset-2">
                <input class="form-control" type="text" name="target_url" placeholder="검사를 원하는 페이지의 URL을 입력해주세요">
            </div>
            <div class="col-lg-3">
                <button class="bb btn btn-default" onclick="access_check()">접근 가능 확인</button>
            </div>
            <div class="col-lg-6 col-lg-offset-3 centered">
                <br>
                <img id="load_img" src="{% static '/img/loading.gif' %}" style="display:none">
            </div>
            <hr>
            <div class="col-lg-6 col-lg-offset-3 centered">
                <div class="custom-border row mt" id="require_login" style="display:none">
                    
                </div>
                <form method="post"  action="{% url 'vuln:scan_work' %}">
                    <div id="hidden">
            
                    </div>
                    {% csrf_token %}
                    <br>
                    <button id="start" class="bb btn btn-lg" type="submit" value="전송" disabled>검사 시작</button>   
                </form>
            </div>
        </div>
        
        
            
            
          
    </div>

    
    
    
    </div> 
    
    <script>
        function access_check(){
            $("#require_login").hide()
            $("#require_login").empty()
            $("#hidden").empty()
            
            $("#start").attr("disabled", true)
            $.ajax({
                url: "/check/url_access/", 
                data: { 'url': $("input[name=target_url]").val(), csrfmiddlewaretoken: '{{ csrf_token }}'},                
                type: "POST",                            
                dataType: "json",
                beforeSend : function(){$("#load_img").show()},
                complete : function(){
                    $("#load_img").hide()
                    $("#require_login").show()
                },
                success: function(data){
                    if (data.status == 'ok'){
                        // alert('접근 가능')
                       
                        $("#require_login").append("<h3>정상적으로 접근이 가능합니다.</h3>")
                        $("#hidden").append("<input type='hidden' name='content' value='"+btoa(JSON.stringify({'url': $("input[name=target_url]").val()}))+"'>")
                        $("#start").attr("disabled", false)
                    }
                    else if(data.status == 'invalid_url'){
                        // alert(data.status)
                        $("#require_login").append("<h3>접근할 수 없는 URL 입니다.</h3>")
                    }
                    else{
                        // alert(data.status)
                        
                        obj = data.status
                        $("#require_login").append("<h3> 로그인 세션이 필요합니다</h3>")
                        $("#require_login").append("<br><h4> 탐지한 로그인 페이지 </h4> <p>"+obj.act_url+"</p>")
                        // $("#require_login").append("<p> 기본값 있음 : "+Object.keys(obj.data)+"</p>")

                        $("#require_login").append("<h4>사용자 정보 입력</h4>")
                        Object.keys(obj.data_no_val).forEach(function(v){
                            $("#require_login").append("<input class='form-control' type='text' placeholder='"+v+"'name='"+v+"'><br>")
                        })
                        $("#require_login").append("<p id='session_msg'></p>")
                        $("#require_login").append("<button class='bb btn' id='session_test'>세션확인</button>")
                        $('#session_test').on('click', function(){
                            var param = {}
                            param['url'] = $("input[name=target_url]").val(),
                            param['act_url'] = obj.act_url
                            param['data'] = obj.data
                            $('#require_login').children("input").each(function(index, item){
                                param['data'][item.name] = item.value
                            })
                            $("#start").attr("disabled", true)
                            $.ajax({
                                url: "/check/session_test/", 
                                data: {'content':JSON.stringify(param), csrfmiddlewaretoken: '{{ csrf_token }}'},
                                type: "POST",                            
                                dataType: "json",                        
                                success: function(data){
                                    // alert(JSON.stringify(data))
                                    if (data.status){
                                        $("#hidden").append("<input type='hidden' name='content' value='"+btoa(JSON.stringify(param))+"'>")
                                        $("#start").attr("disabled", false)
                                        $("#session_msg").attr("class", 'bg-success')
                                        $("#session_msg").text("세션이 확인되었습니다.")
                                    }
                                    else {
                                        $("#session_msg").attr("class", 'bg-danger')
                                        $("#session_msg").text("입력하신 정보로 세션을 얻을 수 없습니다.")
                                    }
                                }
                            })
                        })
                    }
                }
                
            })
            .fail(function(data, textStatus, errorThrown){
                $("#require_login").append("<h3>존재하지 않는 URL 입니다.</h3>")
            })
        }
    
    </script>

{% endblock %}

mysite/vulnscan/templates/vulnscan/scan_work.html
{% extends 'vulnscan/base.html' %}
{% load static %}

{% block contents %}
    <div class="container pt">
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3 centered">
                <h4>검사 준비 > <span class="highlight">검사 중</span> > 검사 완료 > 완료</h4>
                <h1>Vulnerability Check</h1>
                
            </div>
        </div>  
        <div class="row">
            <div class="custom-border" style="height:500px; overflow:auto;" >
                
                <table class="table centered" id="result_table" style="table-layout:fixed">
                    <tr>
                        <th style="width:30%">검사 항목</th>
                        <th style="width:10%">상태</th>
                        <th style="width:60%">요약 정보</th>
                    </tr>
                </table>
                <div id="result"></div>
            </div>
            <div class="col-lg-2 centered">
                <h3> 검사 진행도 </h3>
            </div>
            <div class="col-lg-10">
                <br>
                <div class='progress-wrapper'>
                    <div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
                    <div id="progress-bar-message">Waiting for progress to start...</div>
                </div>
                <br>
            </div>
        </div>
        
        <div class="row">
            <br>
            <div class="col-lg-6 col-lg-offset-3  centered">
                <button class="bb btn btn-lg" id="next" onClick="location.href='{% url 'vuln:scan_end' task_id %}'" style="display:none;">결과 확인</button>
                <button class="bb btn btn-lg" id="previous" onClick="location.href='{% url 'vuln:scan_start'%}'" style="display:none;">돌아가기</button>
            </div>
        </div>  
        
        
        
    </div>


    <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
    <script>
        function xss_filter(content){
            return content.replaceAll(/</g, "&lt;").replaceAll(/>/g, "&gt;")
        }

        function customProgress(progressBarElement, progressBarMessageElement, progress){
            taskNumber = parseInt(progress.current)
            taskPercentage = taskNumber / progress.total * 100
            if(taskPercentage>=100){ $("#next").show();}

            progressBarElement.style.backgroundColor = "#68a9ef"
            progressBarElement.style.width = taskPercentage + "%"

            data = JSON.parse(progress.description)
            
            
            progressMessage = xss_filter(data.content+"")
            progressBarMessageElement.innerHTML = "";

            if($("#result_table tr:last>td:eq(0)").html() != data.name){
                if (data.status == "탐지"){
                    $("#result_table").append("<tr class='danger'><td>"+data.name+"</td><td>"+data.status+"</td><td style='overflow:hidden; text-overflow: ellipsis; white-space:nowrap;'>"+progressMessage+"</td></tr>");
                }
                else {
                    $("#result_table").append("<tr class='success'><td>"+data.name+"</td><td>"+data.status+"</td><td style='overflow:hidden; text-overflow: ellipsis; white-space:nowrap;'>"+progressMessage+"</td></tr>");
                }
                
            }
            
        }
        function customSuccess(resultElement, result) {
            $("#next").show();
        }
        function csError(resultElement, result) {
            $("#previous").show();
        }
        document.addEventListener("DOMContentLoaded", function () {
            var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
            CeleryProgressBar.initProgressBar(progressUrl, {
                onProgress: customProgress,
                onSuccess: customSuccess,
                onError: csError,
            });
        });
        
    </script>
    
    
{% endblock %}